# Site settings
title: Miftahur Ridho
description: 'Mahasiswa Sistem Informasi, Fakultas Sains dan Teknologi, UIN SUSKA RIAU'
url: 'http://sif.uin-suska.ac.id/' 
baseurl: '/sif uin-suska/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Miftahur Ridho'
  email: mifridho@gmail.com
  twitter_username: mifridho
  github_username:  miftahurridho
  linkedin_username:  miftahurridho

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
